### ISSUE TITLE
Error with PEPPOL-EN16931-UBL-SG-Conformant.xsl

### ISSUE THREAD

**Issue by sg20200909** [SG-PEPPOL/SG-PEPPOL-Specifications#5]
erro msg pops when validating  with above {"The context item for axis step root/element() is absent. Found while atomizing the second operand of '='"}

CEN-EN16931-UBL-SG-Conformant.xsl works fine

**Comment by MartinForsberg-Ecru** [comment]
Can you provide a sample file which is causing this error? Also, which XSLT transformer are you using?

**Comment by sg20200909** [comment]
sorry sir..my bad.. was using the wrong processor for the xslt..works fine..tq..
